DB_FILENAME = r"test.db"

CLIENT_TABLE_NAME = "Client"
CLIENT_TABLE_FIELD_ID = "ID"  # Primary
CLIENT_TABLE_FIELD_USERNAME = "username"
CLIENT_TABLE_FIELD_DATE_OF_BIRTH = "date_of_birth"
# CLIENT_TABLE_FIELD_FULLNAME = "fullname"

LOCATION_TABLE_NAME = "Location"
LOCATION_TABLE_FIELD_ID = "ID"  # Primary key
LOCATION_TABLE_FIELD_COUNTRY = "country"
LOCATION_TABLE_FIELD_CITY = "city"
LOCATION_TABLE_FIELD_ZIP = "zip"

REFILL_STATION_HISTORY_TABLE_NAME = "Refill_station_history"
REFILL_STATION_HISTORY_TABLE_FIELD_REFILL_STATION_ID = "rs_id"  # Primary key
REFILL_STATION_HISTORY_TABLE_FIELD_DATE = "date"  # Primary key
REFILL_STATION_HISTORY_TABLE_FIELD_AMOUNT_OF_FREE_CHARGER = "amount_of_free_chargers"
# REFILL_STATION_HISTORY_TABLE_FIELD_ID = "ID"
# CHARGE_EVENT_TABLE_FIELD_CAR_ID = "c_id"
# CHARGE_EVENT_TABLE_FIELD_COST = "cost"
# CHARGE_EVENT_TABLE_FIELD_CHARGE_TIME = "charge_time"
# CHARGE_EVENT_TABLE_FIELD_ARRIVAL_TIME = "arrival_time"

REFILL_STATION_TABLE_NAME = "Refill_Station"
REFILL_STATION_TABLE_FIELD_ID = "ID"  # Primary key
REFILL_STATION_TABLE_FIELD_LAT = "lat"
REFILL_STATION_TABLE_FIELD_LNG = "lng"
REFILL_STATION_TABLE_FIELD_TOTAL_AMOUNT_OF_CHARGERS = "total_amount_of_chargers"
# REFILL_STATION_TABLE_FIELD_AMOUNT_OF_FREE_CHARGERS = "amount_of_free_chargers"
# REFILL_STATION_TABLE_FIELD_AMOUNT_OF_TAKEN_ENERGY = "amount_of_taken_energy"

CAR_LOG_TABLE_NAME = "Car"
CAR_LOG_TABLE_FIELD_CHARGE_LEVEL = "charge_level"
CAR_LOG_TABLE_FIELD_ALL_CARS = "ac_id"  # Primary
CAR_LOG_TABLE_FIELD_LAT = "lat"
CAR_LOG_TABLE_FIELD_LNG = "lng"
CAR_LOG_TABLE_FIELD_TIME = "time"  # Primary
CAR_LOG_TABLE_FIELD_ORDER_ID = "o_id"
# CAR_LOG_TABLE_FIELD_UID = "UID"

ORDER_TABLE_NAME = "Order_table"
ORDER_TABLE_FIELD_ID = "ID"  # Primary key
ORDER_TABLE_FIELD_STARTING_POSITION_LAT = "st_pos_lat"
ORDER_TABLE_FIELD_STARTING_POSITION_LNG = "st_pos_lng"
ORDER_TABLE_FIELD_DESTINATION_LAT = "destination_lat"
ORDER_TABLE_FIELD_DESTINATION_LNG = "destination_lng"
ORDER_TABLE_FIELD_END_TIME = "end_time"
ORDER_TABLE_FIELD_START_TIME = "start_time"
ORDER_TABLE_FIELD_PRICE = "price"
ORDER_TABLE_FIELD_SATISFACTION = "satisfaction"
ORDER_TABLE_FIELD_MANAGER_ID = "manager_id"
ORDER_TABLE_FIELD_CLIENT_ID = "client_id"
ORDER_TABLE_FIELD_STATE = "state"  # TODO not sure do we need this, may be redundant
# ORDER_TABLE_FIELD_ALL_CARS_ID = "all_car_id"

MANAGER_TABLE_NAME = "Manger"
MANAGER_TABLE_FIELD_ID = "ID"  # Primary
MANAGER_TABLE_FIELD_NAME = "name"
MANAGER_TABLE_PHONE = "phone"

VIDEO_TABLE_NAME = "Video"
# VIDEO_TABLE_FIELD_ID = "ID"
VIDEO_TABLE_FIELD_DURATION = "duration"
VIDEO_TABLE_FIELD_START_TIME = "start_time"  # Primary key
VIDEO_TABLE_FIELD_CONTENT = "content"
VIDEO_TABLE_FIELD_ALL_CARS_ID = "ac_id"  # Primary key

RELATION_TABLE_LIVES_AT_NAME = 'Lives_At'
RELATION_TABLE_FIELD_LIVES_AT_CLIENT_ID = 'c_id'
RELATION_TABLE_FIELD_LIVES_AT_LOCATION_ID = 'l_id'

ALL_CARS_TABLE_NAME = "All_Cars"
ALL_CARS_FIELD_ID = "id"
ALL_CARS_FIELD_COLOR = "color"
ALL_CARS_FIELD_NUMBER = "number"
ALL_CARS_FIELD_MODEL = "model"

PAYMENT_TABLE_NAME = "Payment_table"
# PAYMENT_TABLE_FIELD_ID = "id"
PAYMENT_TABLE_FIELD_ORDER_ID = "o_id"
PAYMENT_TABLE_FIELD_HASH_CREDIT_CARD = "credit_card"
